https://docs.docker.com/engine/install/debian/
https://fitech101.aalto.fi/web-software-development/9-working-with-containers/2-dockerfile-and-docker-compose/
https://docs.docker.com/engine/reference/commandline/compose_up/
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04
https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-10
https://docs.docker.com/storage/volumes/
https://codetryout.com/docker-compose-copy-file-to-container/
https://laracasts.com/discuss/channels/general-discussion/larevel-sail-up-docker-unsupported-config-option-for-servicesmeilisearch-platform
https://stackoverflow.com/questions/48588449/docker-issue-bin-sh-pip-not-found
https://blog.codecentric.de/running-robot-framework-in-your-own-docker-container
https://docs.docker.com/engine/reference/commandline/restart/
https://docs.docker.com/engine/reference/commandline/compose_build/
https://docs.docker.com/engine/reference/commandline/exec/
https://forum.robocorp.com/t/modulenotfounderror-no-module-named-rpa-when-running-test-via-command-line/2066
https://docs.docker.com/config/containers/start-containers-automatically/
https://github.com/robocorp/rpaframework/issues/194
https://linuxhandbook.com/docker-restart-policy/
https://docs.docker.com/engine/reference/commandline/exec/
https://www.baeldung.com/ops/docker-compose-interactive-shell
https://stackoverflow.com/questions/68677247/importing-library-rpa-browser-selenium-failed-modulenotfounderror-no-module
https://forum.robotframework.org/t/error-message-could-not-connect-to-the-playwright-process/1071/7
https://blog.hubspot.com/website/update-node-js
https://stackoverflow.com/questions/36884991/how-to-rebuild-docker-container-in-docker-compose-yml
https://stackoverflow.com/questions/8967902/why-do-you-need-to-put-bin-bash-at-the-beginning-of-a-script-file
