# docker compose up -d
services:
  web:
  image: nginx:latest
  ports:
    - "8090:80"
  playw:
    # 
    #
    #image: 
    build: .
    command: 'mkdir -p WEB && robot -d WEB /home/ptp_play.robot'
    volumes:
      - /home/te/:/home/
    restart: always
    # expose:
    #   - 8090
      
volumes:
  /home/te/:
# docker cp <containerId>:WEB /home/ -------> to the bash
#